; Custom PHP configuration untuk pembelajaran
; Semua error ditampilkan agar celah SQL Injection terlihat jelas

display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Batasan upload (sengaja dibesarkan untuk DoS simulation)
upload_max_filesize = 200M
post_max_size = 200M
max_execution_time = 300

; Celah tambahan: allow_url_include untuk bahan RFI/LFI
allow_url_include = On
allow_url_fopen = On
